# Generated by Django 3.1.5 on 2021-02-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210207_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
