# Generated by Django 3.1.5 on 2021-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210207_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.FileField(upload_to='uploads/', verbose_name='image'),
        ),
    ]
